server:
  profiles:
    active: dev



---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: prod
  application:
    name: microservice-product-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 当前数据源操作类型 driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8 # 数据 库名称
    username: root
    password: 293415
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.mengxuegu.springcloud.mapper: debug

eureka:
  client:
    registerWithEureka: true
    # 服务注册开关
    fetchRegistry: true
    # 服务发现开关
    serviceUrl:
      # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: microservice-product-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 当前数据源操作类型 driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据 库名称
    username: root
    password: 293415
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.mengxuegu.springcloud.mapper: debug

eureka:
  client:
    registerWithEureka: true
    # 服务注册开关
    fetchRegistry: true
    # 服务发现开关
    serviceUrl:
      # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true